### ISSUE TITLE
Option to not drop Mongo collections

### ISSUE THREAD

**Issue by jvrfaria** [ClearcodeHQ/pytest-mongo#465]
I'd like do use pytest-mongo plugin on my functional tests but I can't because I share the DB under test with another colleagues and the teardown of mongodb fixture always drop all collection from the DB instance, that would be inconvenient.

The plugin could provide one more config option (with CLI, pytest.ini or factory arg) that blocks or not the collections drop.

**Comment by fizyk** [comment]
Hi @jvrfaria 
It's been years since I've touched anything Mongo related. but one thing I know, you definitely do not want to leave tests data hanging in between tests (unless it's a smoketest with a series of test-steps)

Does everyone of you have separate database... database? Instead of drop or not, plugin could keep a list of tables to operate on.

Out of curiosity, why do you are database instance between you?
